In [9]:
import numpy as np
a=np.array([20,30,40,50])
b=np.array([60,70,80,90])
print(a+b)
print(np.add(a,b)) 

[ 80 100 120 140]
[ 80 100 120 140]


In [12]:
a=np.array([20,30,40,50])
b=np.array([60,70,80,90])
print(a-b)
print(np.subtract(a,b))

[-40 -40 -40 -40]
[-40 -40 -40 -40]


In [13]:
a=np.array([20,30,40,50])
b=np.array([60,70,80,90])
print(a*b)
print(np.multiply(a,b))

[1200 2100 3200 4500]
[1200 2100 3200 4500]


In [14]:
a=np.array([20,30,40,50])
b=np.array([60,70,80,90])
print(a/b)
print(np.divide(a,b))

[0.33333333 0.42857143 0.5        0.55555556]
[0.33333333 0.42857143 0.5        0.55555556]


In [15]:
a=np.array([20,30,40,50])
b=np.array([3])
print(np.power(a,b))

[  8000  27000  64000 125000]


In [16]:
a=np.array([2,3,4,5])
b=np.array([2])
print(np.power(a,b))

[ 4  9 16 25]


In [19]:
 a=np.array([ 4,9,16,25])
print(np.sqrt(a))

[2. 3. 4. 5.]
