In [1]:
print("sapna")

sapna


In [2]:
import numpy as np
a=np.array([10,20,30,40])
print(a)
print(type(a))

[10 20 30 40]
<class 'numpy.ndarray'>


In [3]:
a=np.array([[20,30,40,60,60,70],[25,56,78,90,45,44]])
print(a)
print(type(a))

[[20 30 40 60 60 70]
 [25 56 78 90 45 44]]
<class 'numpy.ndarray'>


In [11]:
a=np.array([[10,40,50,80],[30,40,60,70],[23,45,67,89]])
print(a)
print(type(a))

[[10 40 50 80]
 [30 40 60 70]
 [23 45 67 89]]
<class 'numpy.ndarray'>


In [18]:
a=np.array([10,20,30,40])
print(a[0:3])

[10 20 30]


In [21]:
a=np.array([10,20,30,40])
print(a[:3])

[10 20 30]


In [22]:
a=np.array([10,20,30,40])
print(a[0:])

[10 20 30 40]


In [25]:
a=np.array([[10,40,50,80],[30,40,60,70]])
print(a[0:2,0:2])

[[10 40]
 [30 40]]


In [28]:
a=np.array([[10,40,50,80],[30,40,60,70]])
print(a[0:3,0:2])
print(type(a))

[[10 40]
 [30 40]]
<class 'numpy.ndarray'>


In [29]:
a=np.array([[10,40,50,80],[30,40,60,70]])
print(a[0:2,0:3])
print(type(a))

[[10 40 50]
 [30 40 60]]
<class 'numpy.ndarray'>


In [30]:
a=np.array([[10,40,50,80],[30,40,60,70]])
print(a[0,0:2])
print(type(a))

[10 40]
<class 'numpy.ndarray'>


In [31]:
# a=np.array([[10,40,50,80],[30,40,60,70],[23,45,67,89]])
# print(a[2,2])
# print(type(a))

67
<class 'numpy.ndarray'>


In [38]:
# ATTRIBUTES/ INSPECTING AN NUMPY IN NUMPY
a=np.array([[10,40,50,80],[30,40,60,70],[23,45,67,89]])
print(np.shape(a))
print(np.size(a))
print(np.ndim(a))               # number of array dimension dimension.
print(a.dtype)
print(a.astype(float))
print(len(a))

(3, 4)
12
2
int32
[[10. 40. 50. 80.]
 [30. 40. 60. 70.]
 [23. 45. 67. 89.]]
3
