In [1]:
import numpy as np
l1=[2,3,4,5]
l2=[6,7,8,9]
print(l1+l2)

[2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
l1=[2,3,4,5]
l2=6
print(l1*l2)

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]


In [6]:
a=np.array([20,30,40,50])
b=np.array([60,70,80,90])
print(a)
print(b)
print(a+b)


[20 30 40 50]
[60 70 80 90]
[ 80 100 120 140]


In [7]:
a=np.array([20,50,70,80])
b=np.array([5])
print(a*b)

[100 250 350 400]


In [8]:
a=np.array([40,50,"60"])
print(a)

['40' '50' '60']


In [9]:
c=np.array([34,6,7.0])
print(c)

[34.  6.  7.]


In [11]:
a=np.array([[25,35,45,65,55],[34,29,47,23,33]])
print(a)

[[25 35 45 65 55]
 [34 29 47 23 33]]


In [ ]:
a=np.array([[20,30,40,50],[30,50,70]])       #this code shoe error because the  number  of array element/column are not same in here. 
print(a)

In [12]:
a=np.array([[20,30,40,50],[100,200,40,60],[12,34,16,17]])
print(a)

[[ 20  30  40  50]
 [100 200  40  60]
 [ 12  34  16  17]]


In [ ]:
a=np.array([[25,35,65,55],[34,29,47,23,33]])      #this code shoe error because the  number  of array element/column are not same in here. 
print(a)