In [9]:
import numpy as np
a=[30,40,50]
b=[5,5,3]
print(a+b)


[30, 40, 50, 5, 5, 3]


In [10]:
a=[30,40,50]
b=[5,5,3]
print(np.array(a+b))

[30 40 50  5  5  3]


In [11]:
a=[30,40,50]
b=[5,5,3]
print(np.concatenate([a,b]))

[30 40 50  5  5  3]


In [15]:
a=[30,40,50],[50,20,40]
b=[30,50,70],[30,60,70]
print(np.concatenate([a,b]))

[[30 40 50]
 [50 20 40]
 [30 50 70]
 [30 60 70]]


In [22]:
# a=[30,40,50],[50,20,40]
# b=[30,50,70],[30,60,70]
# print(np.concatenate([a,b]),axis=01)

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (1843812711.py, line 3)

In [25]:
a=[30,40,50],[50,20,40]
b=[30,50,70],[30,60,70]
print(np.hstack([a,b]))

[[30 40 50 30 50 70]
 [50 20 40 30 60 70]]


In [26]:
a=[30,40,50],[50,20,40]
b=[30,50,70],[30,60,70]
print(np.vstack([a,b]))

[[30 40 50]
 [50 20 40]
 [30 50 70]
 [30 60 70]]


In [33]:
# SPLIT
a=np.array([20,30,40,50,60,80])
b=(np.array_split(a,3))
print(b)

[array([20, 30]), array([40, 50]), array([60, 80])]


In [34]:
a=np.array([20,30,40,50,60,80])
print(b[1])

[40 50]


In [36]:
a=np.array([20,30,40,50,60,80])
print=(np.array_split(a,5))
print(b)

TypeError: 'list' object is not callable